### ISSUE TITLE
Fullscreen mode works improperly

### ISSUE THREAD

**Issue by r0thko** [Dirli/videos2#2]
Hello,
the fullscreen mode is working improperly no matter how I enter : with double-click on the screen or fullscreen window button.

![Screenshot from 2020-12-14 18 05 24](https://user-images.githubusercontent.com/74073424/102112140-92af0880-3e37-11eb-9e25-5fd041d33fa0.png)

**Comment by Dirli** [comment]
and if you take not the master but the latest release, how does it behave?
I recently changed the output of the video image a lot, and everything works fine on the latest versions, but I don't have the opportunity to check on the old versions
https://github.com/Dirli/videos2/releases/tag/0.9.1

**Comment by Dirli** [comment]
unfortunately, the freshness of the EOS is a very big problem. and it's a pity that the developers are in no hurry to update it, and it's technically a little difficult for me to roll back to ubuntu 18.04 (for full testing)

**Comment by r0thko** [comment]
I confirm the issue isn't present in 0.9.1, thank you.

**Comment by Dirli** [comment]
I needed support for hardware acceleration, and initially I tested the player on intel graphics, then my laptop broke and continued on nvidia, at some point I got confused where it worked correctly and where it broke due to the update (gtsreamer) or change hardware. I agree that this is not quite correct, but in view of the small popularity, I adhere to the principle "everything works for me". now I don't see the point in adapting to EOS5 because it is outdated and will still be updated sometime. I waiting for the release of the 6th version to create a PPA
debian testing
mutter 36
gstreamer 1.18
PS if it is not difficult, please specify whether it works with hardware acceleration enabled and without (there is an option in the settings) or only without?

**Comment by r0thko** [comment]
sure, but please point me where I can enable/disable it, I don't see such option neither in videos2 or eOS settings.

**Comment by Dirli** [comment]
![screen (1)](https://user-images.githubusercontent.com/15650716/102121747-86d23f00-3e55-11eb-8cc4-b569a7e45e58.png)
enable "use vaapi", and restart player (for version 0.9.1, this setting is not relevant in the master)

**Comment by r0thko** [comment]
it works good when I enable this option and restart the player :)
